spring.application.name=dcp-be
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:https://id.smartsolutionvn.com.vn/realms/ssvn}

spring.datasource.url=jdbc:mariadb://mariadb.smartsolutionvn.com.vn:33060/ssw
spring.datasource.username=app
spring.datasource.password=Ssvn!2025
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ==============================
# KEYCLOAK
# ==============================
app.keycloak.base-url=${KEYCLOAK_BASE_URL:https://id.smartsolutionvn.com.vn}
app.keycloak.realm=${KEYCLOAK_REALM:ssvn}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID:ssvn-platform-client-id}
app.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:cn7crCkSWaXBcmWzDCxF2S2qq9jZ9hLN}

# ==============================
# AUTH
# ==============================
app.auth.backend-redirect-uri=${BACKEND_REDIRECT_URI:http://localhost:8080/api/auth/callback}
app.auth.frontend-redirect-uri=${FRONTEND_REDIRECT_URI:http://localhost:4200}
